In [2]:
import pandas as pd

books = {
    'Book Title': ['The Great Gatsby', 'To Kill a Mockingbird', '1984', 'Pride and Prejudice', 'The Catcher in the Rye'],
    'Author': ['F. Scott Fitzgerald', 'Harper Lee', 'George Orwell', 'Jane Austen', 'J.D. Salinger'],
    'Genre': ['Classic', 'Classic', 'Dystopian', 'Classic', 'Classic'],
    'Price': [10.99, 8.99, 7.99, 11.99, 9.99],
    'Copies Sold': [500, 600, 800, 300, 450]
}

books_df = pd.DataFrame(books)

In [3]:
#Use head() to view the first few rows of the DataFrame.
books_df.head()

               Book Title               Author      Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450

In [4]:
#Use describe() to get a statistical summary of the numerical columns.
books_df.describe()

           Price  Copies Sold
count   5.000000     5.000000
mean    9.990000   530.000000
std     1.581139   185.741756
min     7.990000   300.000000
25%     8.990000   450.000000
50%     9.990000   500.000000
75%    10.990000   600.000000
max    11.990000   800.000000

In [5]:
#Use info() to get a concise summary of the DataFrame, including the number of non-null entries in each column.
books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Book Title   5 non-null      object
 1   Author       5 non-null      object
 2   Genre        5 non-null      object
 3   Price        5 non-null      float64
 4   Copies Sold  5 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 328.0+ bytes

In [9]:
#Sort the DataFrame based on the Price.
sorted_books_df = books_df.sort_values(by = "Price", ascending = True)
sorted_books_df

               Book Title               Author      Genre  Price  Copies Sold
2                    1984        George Orwell  Dystopian   7.99          800
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
3     Pride and Prejudice          Jane Austen    Classic  11.99          300

In [10]:
##Sort the DataFrame based on the Copies Sold.
sorted_books_df = books_df.sort_values(by ="Copies Sold", ascending = False)
sorted_books_df

               Book Title               Author      Genre  Price  Copies Sold
2                    1984        George Orwell  Dystopian   7.99          800
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450
3     Pride and Prejudice          Jane Austen    Classic  11.99          300

In [11]:
# Filter the books by a specific Genre.
books_df[books_df["Genre"] == "Classic"]

               Book Title               Author    Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald  Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee  Classic   8.99          600
3     Pride and Prejudice          Jane Austen  Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger  Classic   9.99          450

In [12]:
# Filter the books with Price above a certain threshold.
books_df[books_df["Price"] >= 9]

               Book Title               Author    Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald  Classic  10.99          500
3     Pride and Prejudice          Jane Austen  Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger  Classic   9.99          450

In [14]:
#Group the books by Author and sum up the Copies Sold.
books_df.groupby("Author")["Copies Sold"].sum()

Author
F. Scott Fitzgerald    500
George Orwell          800
Harper Lee             600
J.D. Salinger          450
Jane Austen            300
Name: Copies Sold, dtype: int64