In [1]:
# Getting Started with PANDAS
# To start using Pandas, you need to import it into your Python environment, typically with the alias pd:

import pandas as pd

In [ ]:
# Understanding SERIES and DATAFRAMES
# Pandas has two primary data structures:

In [ ]:
#1 SERIES: A one-dimensional array-like object capable of holding any data type.
# Think of it as a column in a spreadsheet.
data_1 = pd.Series([1, 3, 5, 7, 9])

In [2]:
# DataFrames: A two-dimensional, size-mutable, and potentially heterogeneous tabular data structure 
# with labeled axes (rows and columns). It’s like a spreadsheet or SQL table.

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 32],
    'City': ['New York', 'Paris', 'Berlin', 'London']
}
df = pd.DataFrame(data)

In [3]:
df.head()   # Displays the first 5 rows by default

    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   32    London

In [22]:
data['Age']

[28, 34, 29, 32]

In [ ]:
# Access data in a DataFrame by referencing the column name:

df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [4]:
df.describe()

             Age
count   4.000000
mean   30.750000
std     2.753785
min    28.000000
25%    28.750000
50%    30.500000
75%    32.500000
max    34.000000

In [6]:
df.to_csv('mydata.csv',index=False)

In [8]:
other_df = pd.read_csv('mydata.csv')
other_df.head()

    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   32    London

In [30]:
#df.tail() : Displays the last 5 rows by default
df.tail(2)        # displays the last 2 rows

    Name  Age    City
2  Peter   29  Berlin
3  Linda   32  London

In [31]:
df['Age'] >= 30

0    False
1     True
2    False
3     True
Name: Age, dtype: bool

In [32]:
# Filtering: Select rows based on a certain condition.
df[df['Age'] >= 30]         # Selects rows where age is greater than 30

    Name  Age    City
1   Anna   34   Paris
3  Linda   32  London

In [33]:
# Filters the DataFrame to people aged 30 or older, then selects only their Name
df[df['Age'] >= 30]['Name']

1     Anna
3    Linda
Name: Name, dtype: str

In [37]:
# Sorting: Sort data by a specific column.
sorted_df = df.sort_values(by="Name")
sorted_df

    Name  Age      City
1   Anna   34     Paris
0   John   28  New York
3  Linda   32    London
2  Peter   29    Berlin

In [9]:
otherdf

    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   32    London

In [39]:
otherdf['Spend'] = [100,200,140,145]

In [40]:
otherdf

    Name  Age      City  Spend
0   John   28  New York    100
1   Anna   34     Paris    200
2  Peter   29    Berlin    140
3  Linda   32    London    145

In [41]:
otherdf.iloc[1]

Name      Anna
Age         34
City     Paris
Spend      200
Name: 1, dtype: object

In [44]:
otherdf.loc[1,"Age"] = 29

In [45]:
otherdf

    Name  Age      City  Spend
0   John   28  New York    100
1   Anna   29     Paris    200
2  Peter   29    Berlin    140
3  Linda   32    London    145

In [47]:
otherdf.groupby('Age')['Spend'].mean()

Age
28    100.0
29    170.0
32    145.0
Name: Spend, dtype: float64